### Transforming Code into idiomatic python
- Replace traditional index manupulation with python core looping idiomatic

In [1]:
# looping over a range of numbers - traditional approch
for i  in [0,1,2,3,4,5]:
    print(i**2,end=" ")

0 1 4 9 16 25 

In [3]:
#Idiomatic programming 
for i in range(8):
    print(i**2,end=" ")

0 1 4 9 16 25 36 49 

### Looping over a collection

In [4]:
colors = ['red','green','yellow','purple']
for i in range(len(colors)):
    print(colors[i],end=" ")
    

red green yellow purple 

In [7]:
for color in colors:
    print(color,end=" ")

red green yellow purple 

### Looping backwards


In [8]:
colors = ['red','green','yellow','purple']
for i in range(len(colors)-1,-1,-1):
    print(colors[i],end=" ")

purple yellow green red 

In [9]:
for color in reversed (colors):
    print(color,end=" ")

purple yellow green red 

### Looping in sorted list 


In [13]:
colors = ['red','green','yellow','purple']
for color in sorted (colors):
    print(color,end=" ")
    

green purple red yellow 

In [14]:
colors = ['red','green','yellow','purple']
for color in sorted (colors,reverse=True):
    print(color,end=" ")
    

yellow red purple green 

###
- if x <= y and y <=z:
- if x<=y<=z:
- if x==True:
- if x:

### Pandas

In [15]:
import pandas as pd

In [16]:
dt = {'Id':[11,12,13,14,15],
     'first_name':['A','B','C','D','E'],
     'company':['aa','bb','cc','dd','ee'],
     'address':['Hyd','Hyd','Hyd','Hyd','Hyd']}
mydt = pd.DataFrame(dt)

In [17]:
print(mydt)

   Id first_name company address
0  11          A      aa     Hyd
1  12          B      bb     Hyd
2  13          C      cc     Hyd
3  14          D      dd     Hyd
4  15          E      ee     Hyd


In [23]:
import os
os.getcwd()

'C:\\Users\\student'

In [22]:
os.chdir("C:\\Users\\student")# saves to certain location

In [24]:
mydt.to_csv('WorkingFile.csv',index=False)

### Reading the data from csv file


In [25]:
mydata = pd.read_csv('workingfile.csv')

In [26]:
print(mydata)

   Id first_name company address
0  11          A      aa     Hyd
1  12          B      bb     Hyd
2  13          C      cc     Hyd
3  14          D      dd     Hyd
4  15          E      ee     Hyd


In [27]:
pwd

'C:\\Users\\student'

In [32]:
mydata1 = pd.read_csv('WorkingFile.csv',skiprows=1,
                    names=["custId","Name","Company","Address"])

In [33]:
print(mydata1)

   custId Name Company Address
0      11    A      aa     Hyd
1      12    B      bb     Hyd
2      13    C      cc     Hyd
3      14    D      dd     Hyd
4      15    E      ee     Hyd


In [39]:
mydata2 = pd.read_csv('WorkingFile.csv',skiprows=[1,2,3],
                       names=["CustId","Name","Company","Address"])

In [40]:
print(mydata2)

  CustId        Name  Company  Address
0     Id  first_name  company  address
1     14           D       dd      Hyd
2     15           E       ee      Hyd


### print only two columns

### print the large  value from custid column -- max

### print the least  value from custid column -- min

### average of custid column -- sum(li)/len(li)


### Numpy - Working with multi Dimensional array
 - numpy arrays is a bit like python list
 - numpy is also one of data structure
 - numpy short name for "numeric python" or "numerical python"

In [41]:
import numpy as np

In [42]:
li = [1,2,3,4,5]
print(li,end=" ")

[1, 2, 3, 4, 5] 

In [43]:
array = np.array(li)
print(array)

[1 2 3 4 5]


In [44]:
a1 = np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2 = np.array([(1,2),(2,3),(4,5)])
print(a2.shape)

(2, 3)
(3, 2)


In [45]:
a1 = np.array([(1,2,3),(4,5,6)])
a1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
a1= np.array([(1,2,3)])
a2= np.array([(4,5,6)])
print(np.hstack((a1,a2)))

[[1 2 3 4 5 6]]


In [47]:
a1= np.array([(1,2,3)])
a2= np.array([(4,5,6)])
print(np.vstack((a1,a2)))


[[1 2 3]
 [4 5 6]]
